-- MySQL Script generated by MySQL Workbench
-- Tue Feb 21 10:58:59 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8 ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Customer` (
                                                    `idCustomer` INT NOT NULL,
                                                    `name` VARCHAR(45) NULL,
    PRIMARY KEY (`idCustomer`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`book` (
                                                `idbook` INT NOT NULL,
                                                `titel` VARCHAR(45) NULL,
    `preis` DOUBLE NULL,
    PRIMARY KEY (`idbook`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Transaction` (
                                                       `idTransaction` INT NOT NULL,
                                                       `Customer_idCustomer` INT NOT NULL DEFAULT 0,
                                                       `book_idbook` INT NOT NULL DEFAULT 0,
                                                       `start_bor` DATETIME NULL,
                                                       `end_bor` DATETIME NULL,
                                                       PRIMARY KEY (`idTransaction`),
    INDEX `fk_Transaction_Customer_idx` (`Customer_idCustomer` ASC) VISIBLE,
    INDEX `fk_Transaction_book1_idx` (`book_idbook` ASC) VISIBLE,
    CONSTRAINT `fk_Transaction_Customer`
    FOREIGN KEY (`Customer_idCustomer`)
    REFERENCES `library`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Transaction_book1`
    FOREIGN KEY (`book_idbook`)
    REFERENCES `library`.`book` (`idbook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
